# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x05query\"\x14\n\x04Plan\x12\x0c\n\x04json\x18\x01 \x01(\t\"L\n\x0bRunResponse\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x1d\n\x06status\x18\x02 \x01(\x0e\x32\r.query.Status\x12\x0f\n\x07message\x18\x03 \x01(\t*d\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\r\n\tSUBMITTED\x10\x02\x12\x0b\n\x07RUNNING\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\r\n\tCOMPLETED\x10\x05\x32:\n\x0bQueryRunner\x12+\n\x08RunQuery\x12\x0b.query.Plan\x1a\x12.query.RunResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=122
  _globals['_STATUS']._serialized_end=222
  _globals['_PLAN']._serialized_start=22
  _globals['_PLAN']._serialized_end=42
  _globals['_RUNRESPONSE']._serialized_start=44
  _globals['_RUNRESPONSE']._serialized_end=120
  _globals['_QUERYRUNNER']._serialized_start=224
  _globals['_QUERYRUNNER']._serialized_end=282
# @@protoc_insertion_point(module_scope)
