# Dockerfile
FROM python:3.11-slim


ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    MPLBACKEND=Agg

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


COPY . /app

RUN mkdir -p /app/out /app/data


CMD ["bash","-lc","python -u detect_iforest_pca.py && python -u detect_residuals_and_hybrid.py"]
